# Generated by Django 2.2 on 2019-05-13 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190513_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='user_type',
        ),
    ]
