# Generated by Django 2.2 on 2019-05-13 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_userprofileinfo_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='MEDIA_URL/profile_pics/'),
        ),
    ]
