# Generated by Django 2.2 on 2019-05-17 10:54

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_studydoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studydoc',
            name='document',
            field=models.FileField(blank=True, upload_to=blog.models.content_file_name),
        ),
    ]
