# Generated by Django 2.2 on 2019-05-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190517_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='studydoc',
            name='common',
            field=models.BooleanField(default=False),
        ),
    ]
