# Generated by Django 2.2 on 2019-05-20 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_userprofileinfo_diploma_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studydoc',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='blog.Course'),
        ),
    ]
