# Generated by Django 2.2 on 2019-05-21 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0018_auto_20190520_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(max_length=20)),
                ('lab_number', models.IntegerField(default=0)),
                ('link1', models.URLField(blank=True)),
                ('link2', models.URLField(blank=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lablist', to='blog.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('approve_date', models.DateTimeField(blank=True, null=True)),
                ('real_approve_date', models.DateTimeField(blank=True, null=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labinfo', to='blog.LabInfo')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='labinfo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
