# Generated by Django 2.2 on 2019-05-22 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_lab_labinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labinfo', to='blog.UserProfileInfo'),
        ),
    ]
